/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.diachron.integration.diachronintegrationlayer.services.complexchanges;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author panos
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.diachron.integration.diachronintegrationlayer.services.archiving.ArchiveStoreResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.archiving.ArchivingService.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.archiving.DeirifyResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.complexchanges.ComplexChangeDispatcherResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.complexchanges.ComplexChangeHandler.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.complexchanges.ComplexChangeQueryDispatcherResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.complexchanges.ComplexChangeQueryHandler.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.complexchanges.UnqueueComplexChange.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.complexchanges.UnqueueComplexQueryChange.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.crawling.CrawlingServiceResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.crawling.DispatcherResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.crawling.GenericResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.crawling.UnqueueResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.quality.QualityServiceResource.class);
        resources.add(com.diachron.integration.diachronintegrationlayer.services.validation.RulesTemplateServiceResource.class);
        resources.add(com.diachron.integration.publication.PublicationServiceResource.class);
        resources.add(com.diachron.integration.services.evaluation.DispatcherEvaluateResource.class);
        resources.add(com.diachron.integration.services.evaluation.EvaluateResource.class);
        resources.add(com.diachron.integration.services.evaluation.UnqueueEvaluateResource.class);
    }
    
}
